const TYPES = "build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test";
const CONVENTIONAL = new RegExp(
  `^(${TYPES})(\\([a-z0-9][a-z0-9._/-]*\\))?(!)?: ([a-z0-9][^\\n]*)$`,
  "u",
);

export type MessageValidation = { valid: true } | { valid: false; reason: string };

export function validateCommitSubject(raw: string): MessageValidation {
  const subject = raw.split(/\r?\n/u, 1)[0]?.trim() ?? "";
  if (!subject) return { valid: false, reason: "subject is empty" };
  if (subject.length > 100) return { valid: false, reason: "subject exceeds 100 characters" };
  if (!CONVENTIONAL.test(subject)) {
    return {
      valid: false,
      reason: "expected Conventional Commit: type(scope): lower-case imperative summary",
    };
  }
  if (/[.!?]$/u.test(subject))
    return { valid: false, reason: "subject must not end with punctuation" };
  if (/\b(?:ai-generated|generated by|co-authored-by:.*(?:claude|codex|copilot))\b/iu.test(raw)) {
    return { valid: false, reason: "automatic AI attribution does not belong in commit messages" };
  }
  return { valid: true };
}
